default:
    - override hydra/launcher: local
    - override hydra/output: local

exp:
  seed: 1
  prm1: 10
  prm2: abc
  prm3: ${exp.seed}
  out_dir: seed${exp.seed}prm1${exp.prm1}prm2${exp.prm2}

domain:
  env: swimmer-v0
  api: openaiGym

hydra:
    job:
        name: hydra_demo_${domain.api}_${domain.env}_${exp.seed}